title: Internet of Things (IoT)
description: "F2M3 - Backend programming - IoT"
email: h.braun@ma-web.nl

github_username:  hiddebraun-ma

# Build settings
baseurl: "/F2M3-IoT-Site:"
remote_theme: "pmarsceill/just-the-docs"

#plugins:
#  - jekyll-feed

search_enabled: false
heading_anchors: false


exclude: [ "sources", "start.sh", ".idea" ]

# Config theme
# See: https://pmarsceill.github.io/just-the-docs/docs/configuration/
# color_scheme: dark
search:
  heading_level: 1

logo: "/assets/images/logo.png"
